name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: 🔖 Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Install Zip
        run: sudo apt-get install zip
      - name: Convert library to Arduino IDE compatible format
        run: |
          mkdir -p Bme280/src
          mkdir -p Bme280/examples/TwoWire
          mkdir -p Bme280/examples/FourWire
          mkdir -p Bme280/examples/Settings
          cp LICENSE Bme280
          cp library.properties Bme280
          cp include/Bme280.h Bme280/src
          cp src/Bme280.cc Bme280/src
          cp examples/TwoWire/*.ino Bme280/examples/TwoWire
          cp examples/FourWire/*.ino Bme280/examples/FourWire
          cp examples/Settings/*.ino Bme280/examples/Settings
          zip -r Bme280.zip Bme280/*
      - name: Add release asset Bme280.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: Bme280.zip
          asset_path: ./Bme280.zip
          asset_content_type: application/zip
